export enum Method {
  build = 'build',
  clean = 'clean',
  compile = 'compile',
  decode = 'decode',
  encode = 'encode',
  enrich = 'enrich',
  execute = 'execute',
  get = 'get',
  pipe = 'pipe',
  reshape = 'reshape',
  select = 'select',
  set = 'set',
  validate = 'validate',
  vars = 'vars',
}
