variables:
  - name: node_version
    value: '16.x'

jobs:
  - job: Test
    strategy:
      matrix:
        Linux:
          image_name: ubuntu-latest
        Mac:
          image_name: macOS-latest
        Windows:
          image_name: windows-latest
    pool:
      vmImage: $(image_name)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'

      - script: npm ci
        displayName: Install dependencies

      # Some of the following are only run on Linux to avoid duplication

      - script: npm run lint
        condition: eq(variables['agent.os'], 'Linux')
        displayName: Run linting

      - script: npm run test:cover
        displayName: Run Node tests

      - script: bash <(curl -s https://codecov.io/bash)
        condition: and(succeeded(), eq(variables['agent.os'], 'Linux'))
        displayName: Upload coverage

      - script: |
          set -e
          make image
          docker run stencila/jesta
        condition: and(succeeded(), eq(variables['agent.os'], 'Linux'))
        displayName: Build and run Docker image

  - job: Release
    dependsOn: [Test]
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Install Node.js

      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.x'

      - script: |
          set -e
          npm ci
          make build docs
          npx semantic-release
        env:
          GIT_AUTHOR_NAME: Stencila CI Bot
          GIT_AUTHOR_EMAIL: ci@stenci.la
          GIT_COMMITTER_NAME: Stencila CI Bot
          GIT_COMMITTER_EMAIL: ci@stenci.la
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: Release package

      - task: gitversion/execute@0
        displayName: Determine version

      - task: Docker@2
        displayName: Build and push Docker image
        inputs:
          command: buildAndPush
          containerRegistry: DockerHub
          repository: stencila/jesta
          tags: |
            $(GitVersion.SemVer)
            latest
