jobs:
  - job: test
    strategy:
      matrix:
        linux:
          image_name: ubuntu-latest
          node_version: 14.x
        mac:
          image_name: macOS-latest
          node_version: 14.x
        windows:
          image_name: windows-latest
          node_version: 14.x
    pool:
      vmImage: $(image_name)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'

      - script: npm ci
        displayName: Install dependencies

      # Run linting on Linux only (unnecessary to duplicate by OS)
      - script: npm run lint
        condition: eq(variables['agent.os'], 'Linux')
        displayName: Run linting

      - script: npm run test:cover
        displayName: Run Node tests

      # Upload coverage on Linux only (unnecessary to duplicate by OS)
      - script: bash <(curl -s https://codecov.io/bash)
        condition: and(succeeded(), eq(variables['agent.os'], 'Linux'))
        displayName: 'Upload coverage'

  - job: release
    dependsOn: [test]
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 14.x
        displayName: Install Node.js

      - script: |
          npm ci
          npm run build
          npm run docs
          npx semantic-release
        env:
          GIT_AUTHOR_NAME: Stencila CI Bot
          GIT_AUTHOR_EMAIL: ci@stenci.la
          GIT_COMMITTER_NAME: Stencila CI Bot
          GIT_COMMITTER_EMAIL: ci@stenci.la
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: Release package
