export enum Method {
  build = 'build',
  call = 'call',
  clean = 'clean',
  compile = 'compile',
  convert = 'convert',
  decode = 'decode',
  delete = 'delete',
  downcast = 'downcast',
  encode = 'encode',
  enrich = 'enrich',
  execute = 'execute',
  export = 'export',
  funcs = 'funcs',
  get = 'get',
  import = 'import',
  pipe = 'pipe',
  pull = 'pull',
  read = 'read',
  select = 'select',
  set = 'set',
  upcast = 'upcast',
  validate = 'validate',
  vars = 'vars',
  write = 'write',
}
